version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          build: 'yarn && yarn run build'
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          # record: true # record results on Cypress Dashboard, requires CYPRESS_RECORD_KEY be set
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'sh -c "yarn start" | sleep 30' # start server before running tests
          wait-on: 'http://localhost:3000'
